## import packages

In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

## File processing

In [4]:
# 'consensus_adj_mat.csv'
adj_mat = pd.read_csv('dataset/consensus_adj_mat.csv')
adj_mat = adj_mat.drop(columns=['Unnamed: 0'])
adj_mat

    Akt  Erk  Jnk  Mek  P38  PIP2  PIP3  PKA  PKC  Plcg  Raf
0     0    0    0    0    0     0     0    0    0     0    0
1     0    0    0    0    0     0     0    0    0     0    0
2     0    0    0    0    0     0     0    0    0     0    0
3     0    1    0    0    0     0     0    0    0     0    0
4     0    0    0    0    0     0     0    0    0     0    0
5     0    0    0    0    0     0     0    0    1     0    0
6     1    0    0    0    0     1     0    0    0     1    0
7     1    1    1    1    1     0     0    0    0     0    1
8     0    0    1    1    1     0     0    0    0     0    1
9     0    0    0    0    0     1     0    0    1     0    0
10    0    0    0    1    0     0     0    0    0     0    0

In [5]:
# 'sachs_bin.csv'
sachs_bin = pd.read_csv('dataset/sachs_bin.csv')
sachs_bin = sachs_bin.astype(int) # convert to integer

# Convert each columun into a observed data vector:
X1_obs = sachs_bin['Akt']
X2_obs = sachs_bin['Erk']
X3_obs = sachs_bin['Jnk']
X4_obs = sachs_bin['Mek']
X5_obs = sachs_bin['P38']
X6_obs = sachs_bin['PIP2']
X7_obs = sachs_bin['PIP3']
X8_obs = sachs_bin['PKA']
X9_obs = sachs_bin['PKC']

# CPD's

### Root nodes

In [6]:
# X_7 = PIP3
p_x7 = X7_obs.sum() / len(X7_obs)
p_x7 = np.array([p_x7, 1-p_x7])

# X_8 = PKA
p_x8 = X8_obs.sum() / len(X8_obs)
p_x8 = np.array([p_x8, 1-p_x8])

print ("p(X7) =", p_x7) # [0.37045721 0.62954279]
print ("p(X8) =", p_x8) # [0.30832356 0.69167644]

p(X7) = [0.37045721 0.62954279]
p(X8) = [0.30832356 0.69167644]

### Function ...

In [ ]:
def calculate_conditional_probabilities(Xi_obs, parents, alpha):
    """
    Calculate conditional probabilities P(X1 | X7, X8) using Bayes' theorem.

    inputs:
    Xi_obs (pd.Series): Observed data vector for the target variable Xi.
    parents (np.ndarray): Binary vector indicating the parents (can be 1 or 2) of Xi.
    alpha (float): The alpha parameter = 0.5

    Returns:
    pd.DataFrame: DataFrame containing the conditional probabilities.
    """
    
    return 0